language: python
python:
- '2.7'
install: pip install -r requirements.txt && pip install git+https://github.com/timchen86/gdcmdtools.git@master
script: nosetests -v gdput.py gdget.py gdauth.py gdperm.py test.py
CLIENT_ID:
  secure: E+BEwCJqePiYkLBXGGNUHdRXbzl1XiLYxe2Rq4GVQ0jMMLUYpPngneca6MlcGMEs/gVRkmJ0p16Cj79FnwOE3tVyj6ZcNzZVUpoBeqIzhAv7FAxNpJatjLZ8kcSEPAh9Hsgs3dIM7lMZFZMwuN9vXEdqJTkhvELHhxFpkrrS/9c=
