language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests -sv gdput.py gdget.py gdauth.py gdperm.py test.py
env:
  global:
  - secure: Tj8ZgAFXRCM2AvCyVZd1sWfeyLCZCnnp4FgclFUWSSSUdG9AQ4igbiUxFMUGG5wq6DG5/Hz8FcjTUhbZXalts+vnvy4mCl/jrQogf4mh9MlnM/v7z/NMlhUvFNgwuj+74NgIetfTsl9G3VlH2w0kBoIs7saIOHkR/2cJFra23EE=
  - secure: YZucDdWmiZt8R/XK6LKXWFrPwUIffZi/8Sh3Cs2mP2uVSfWgOM7olRnKd2TOtMGcYq+NTEYwCpS5opfNzaL/LT+WWxKyY/Z3GCWWs9OsVLui42QvcLT7KhinUNY3/yAozBM+uZ/p75xjh5RgtVVu2+tnrO67tzxD/FiWyQV9RG8=
  - secure: AZhrm1kQzScbMxIErpwMUEM00ZFa2q/goqNq4P+D/C/WHrpt5ksz4jAWbGLI/ZJWD+nEsS0DVgAIKJVXTc5J/zaUHaOJAYncUR3oI43Y6OP7x1yVwwshuZ5osLRfhFf9kC2aXmBbvuz04U6eFLYGiPvqAMZwcTT4c028CK2MjMQ=
  - secure: XUY6DDhBm2ERdEjaIcMZ9kIs7DGG3VUOwY90wC4S7GsO4lLX6jWK322uL5vEvXTmtdi6HksMfv5u8kijIlDzHIRX+MDJDMu4jN34bwpxesJ3enJJe6TLJ0qt01loxUznvmJ1dao3dHmg8vpOpkemfb+1584TVvKpnEWN5NDT+ug=
  - secure: A3FnX/RNixMbXLr1gclMEyA2psAg0d5T5E0dfWgLmRX4t9jh8fOg8inNRnhjdxtSfR4XoYzy1rSCjGdFj/zEFoR11bk0jPG70iEt5d+CnCTz8qGaUI7pQOyV99OUozQI9OBXhmnVZKjgPl/CZbTUJV5ufRCIwkWIh8ZMW9nQqmA=
  - secure: ADj9pKFTwAdu4C1gf+cKEcwDsB+dJcfi0d+Tz7o1vw0tT80xXPz5QT9ZyDJTem8znqtleOOrXV0GBWy1OLuYR8M1vHqRmIJX9GaYDfNanhA43d7q5Cg4E3zGmtVgInyZXhvrsbBP4yncIr2VafKqnGWalf6nH9OmqzTzBY3s2O0=
