language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt git+git://github.com:timchen86/gdcmdtools.git@master"
# command to run tests
script: nosetests gdput.py gdget.py gdauth.py gdperm.py
